animation = none

asterisk =

# Allow empty password or not when authenticating
allow_empty_password = false

# Erase password input on failure
clear_password = true

# Initial text to show on the info line (Defaults to hostname)
initial_info_text = null

shutdown_key = F1
restart_key = F2

# Wayland setup command
setup_cmd = /etc/ly/run.sh

# Add wayland specifier to session names
wayland_specifier = false
